### ISSUE TITLE
Evidence content is 'None' for binary evidence stored in the locker

### ISSUE THREAD

**Issue by linuxmonk** [ComplianceAsCode/auditree-framework#95]
## Overview

The feature to allow binary content to be stored in the locker works fine when adding evidences to the locker. However when the checker tries to get the binary content the evidence content is set to None.

## Requirements

* Checker must be able to retrieve evidnence with binary content successfully.

## Approach

The checker tries to load the evidences to perform checks as -

```
with evidences(self, path_to_evidence) as raw_evidences:
  for name, evidence in raw_evidences.items():
    myEvidence = MyEvidence.from_evidence(evidence)
```

In the above scenario, the `myEvidence.content` is empty/None.

## Security and Privacy

N/A

## Test Plan

* Checker must be able to retrieve binary content stored in the evidence locker.

**Comment by alfinkel** [comment]
Sorry, your example isn't clear.  You example implies that you're providing a single path to the evidence `path_to_evidence`.  If that's the case then `raw_evidences` would be a RawEvidence object and not a dictionary.  Can you confirm or provide a clearer example?

**Comment by linuxmonk** [comment]
Sorry about that. Hope this helps. This is a snippet of the whole source that's performing the operation of getting a binary evidence (XLS file) and then converting that to JSON. In the method that converts it to JSON I see an exception because the content is None.

```
 78         csv_paths = self._get_evidence_relpath(
 79             f'{self.locker.local_path}/raw/{GCMEvidence.reldir}/*.csv'
 80         )
 81         xls_paths = self._get_evidence_relpath(
 82             f'{self.locker.local_path}/raw/{GCMEvidence.reldir}/*.xls*'
 83         )
 84         relative_paths = csv_paths + xls_paths
 85         if not relative_paths:
 86             raise Exception('Missing GCM Evidence. Re-run the fetcher')
 87
 88         with evidences(self, relative_paths) as raw_evidences:
 89             for name, evidence in raw_evidences.items():
 90                 gde = GCMEvidence.from_evidence(evidence)
 91                 try:
 92                     json_data = gde.get_json()
 93                 except Exception:
 94                     logging.warn(f'Invalid {name}. Unable to convert to JSON')
 95                     continue
 96                 self._gcm_evidences[name] = json_data
```

**Comment by alfinkel** [comment]
What does get `self._get_evidence_relpath` do?  It's still not clear what exactly you're passing to the `evidences` context manager as paths.  Can you also provide a stack trace if there is one?

**Comment by alfinkel** [comment]
I am somewhat able to replicate your issue.  Although I get a UnicodeDecodeError when I attempt to access the evidence whereas it appears that your evidence is successfully handled but has `None` for content.  That still troubles me a bit.  In any case, I'll work on a fix for handling binary content in the `evidences` context manager and `with_raw_evidences` decorator.

```
Traceback (most recent call last):
  File "/Users/alfinkel/gh/auditree-framework/demo/venv/lib/python3.8/site-packages/compliance/check.py", line 263, in check_failures
    method()
  File "/Users/alfinkel/gh/auditree-framework/demo/demo_examples/checks/test_image_size.py", line 43, in test_image_content
    with evidences(self, 'raw/images/auditree_logo.png') as evidence:
  File "/Users/alfinkel/gh/auditree-framework/demo/venv/lib/python3.8/site-packages/compliance/evidence.py", line 496, in __enter__
    evidence = self._get_evidence(self.from_evidences)
  File "/Users/alfinkel/gh/auditree-framework/demo/venv/lib/python3.8/site-packages/compliance/evidence.py", line 527, in _get_evidence
    evidence = get_evidence_by_path(path, self.locker)
  File "/Users/alfinkel/gh/auditree-framework/demo/venv/lib/python3.8/site-packages/compliance/evidence.py", line 592, in get_evidence_by_path
    evidence = locker.load_content(evidence)
  File "/Users/alfinkel/gh/auditree-framework/demo/venv/lib/python3.8/site-packages/compliance/locker.py", line 505, in load_content
    self._get_file_content(evidence.path, evidence_dt)
  File "/Users/alfinkel/gh/auditree-framework/demo/venv/lib/python3.8/site-packages/compliance/locker.py", line 792, in _get_file_content
    return open(os.path.join(self.local_path, file_path)).read()
  File "/Users/alfinkel/.pyenv/versions/3.8.6/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte
```

**Comment by linuxmonk** [comment]
The `_get_evidence_relpath` just returns a list of relative paths to the evidences. 

```
 56     def _get_evidence_relpath(self, glob_pattern):
 57         """Return list of relative paths of evidences based on glob pattern."""
 58         full_paths = glob.glob(glob_pattern)
 59         relative_paths = [
 60             'raw/' + path.split('/raw/')[-1] for path in full_paths
 61         ]
 62         return relative_paths
```

```
>>> relative_paths
['raw/gcm/consolidated linux 7 dres_20201009.csv', 'raw/gcm/consolidated ssh dres_20201009.csv', 'raw/gcm/consolidated sudo dres_20201009.csv', 'raw/gcm/consolidated tem agent intel_20201009.xlsx']
```

**Comment by linuxmonk** [comment]
I stepped through the code and found the stack trace for the case where I'm seeing errors (xls files). Hope this helps.

```
>> decode [IncrementalDecoder] codecs.py:322
_get_file_content [Locker] locker.py:792
load_content [Locker] locker.py:505
get_evidence [Locker] locker.py:469
get_evidence_by_path evidence.py:597
_get_evidence [evidences] evidence.py:527
_collate_gcm_evidence [GCMSanityCheck] test_gcmevidences.py:88
test_techspec_ref [GCMSanityCheck] test_gcmevidences.py:164
check_failures check.py:263
_callTestMethod [GCMSanityCheck] case.py:633
run [GCMSanityCheck] case.py:676
run [GCMSanityCheck] check.py:270
__call__ [GCMSanityCheck] case.py:736
run [TestSuite] suite.py:122
__call__ [TestSuite] suite.py:84
run [TextTestRunner] runner.py:176
run_checks [CheckMode] runners.py:343
_run [ComplianceCLI] cli_framework.py:171
_validate_and_run [ComplianceCLI] command.py:174
run [ComplianceCLI] command.py:147
run cli_framework.py:179
<module> cli_framework.py:183
```

The error -

```
Traceback (most recent call last):
  File "/Users/linuxmonk/src/cdil/venv/lib/python3.8/site-packages/compliance/locker.py", line 792, in _get_file_content
    return open(os.path.join(self.local_path, file_path)).read()
  File "/Users/linuxmonk/.pyenv/versions/3.8.0/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte
```

**Comment by alfinkel** [comment]
Perfect, thanks!  That matches with what I was able to replicate.  The fix is in PR #96.  Hopefully we'll get it in shortly.

**Comment by alfinkel** [comment]
OK hopefully this is fixed with [v1.10.1](https://pypi.org/project/auditree-framework/).

**Comment by linuxmonk** [comment]
That sounds great. Thanks !

**Comment by alfinkel** [comment]
Closing...  We can reopen if necessary.
